# Generated by Django 5.2.17 on 2026-09-06 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_knowledgecomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentKnowledgeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_prob', models.FloatField(default=0.0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_states', to='courses.enrollment')),
                ('knowledge_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_states', to='courses.knowledgecomponent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'knowledge_component'), name='unique_student_state_per_component')],
            },
        ),
    ]
