# Generated by Django 5.2.17 on 2026-09-06 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_studentknowledgestate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('attempted_at', models.DateTimeField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_attempts', to='courses.enrollment')),
                ('knowledge_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_attempts', to='courses.knowledgecomponent')),
            ],
        ),
    ]
