# Generated by Django 5.2.17 on 2026-09-06 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_learningsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningattempt',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_attempts', to='courses.learningsession'),
        ),
    ]
