# Generated by Django 5.2.16 on 2026-09-08 12:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_learningattempt_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='learningattempt',
            name='external_question_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='learningattempt',
            name='hint_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningattempt',
            name='question_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='learningattempt',
            name='response_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningattempt',
            name='score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='learningattempt',
            name='student_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='goal_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_sessions', to='courses.knowledgecomponent'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentknowledgestate',
            name='evidence_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentknowledgestate',
            name='source',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='studentknowledgestate',
            name='source_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentknowledgestate',
            name='mastery_prob',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
