# Generated by Django 5.2.17 on 2026-09-09 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_learningattempt_attempt_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200)),
                ('problem_set_id', models.CharField(blank=True, max_length=200)),
                ('problem_part', models.IntegerField(blank=True, null=True)),
                ('problem_type', models.CharField(blank=True, max_length=100)),
                ('answer_type', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField()),
                ('fill_in_options', models.JSONField(blank=True, default=list)),
                ('fill_in_answers', models.JSONField(blank=True, default=list)),
                ('multiple_choice_options', models.JSONField(blank=True, default=list)),
                ('multiple_choice_answers', models.JSONField(blank=True, default=list)),
                ('skill_count', models.PositiveIntegerField(default=1)),
                ('source_dataset', models.CharField(blank=True, max_length=100)),
                ('source_license', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_items', to='courses.course')),
                ('knowledge_components', models.ManyToManyField(blank=True, related_name='learning_items', to='courses.knowledgecomponent')),
                ('primary_knowledge_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_learning_items', to='courses.knowledgecomponent')),
            ],
        ),
        migrations.AddField(
            model_name='learningattempt',
            name='learning_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_attempts', to='courses.learningitem'),
        ),
        migrations.AddConstraint(
            model_name='learningitem',
            constraint=models.UniqueConstraint(fields=('course', 'external_id'), name='unique_learning_item_per_course'),
        ),
    ]
