# Generated by Django 5.2.17 on 2026-09-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_learningitem_learningattempt_learning_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningattempt',
            name='saw_answer',
            field=models.BooleanField(default=False),
        ),
    ]
