# Generated by Django 5.2.17 on 2026-09-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_learningattempt_saw_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningattempt',
            name='answer_is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
